insert into SUBSCRIPTION(SUBSCRIBER_NAME,DATE_SUBSCRIBED,BOOK_ID)
values ('John',PARSEDATETIME('12-JUN-2020','d-MMM-yyyy'),'B1212');

insert into SUBSCRIPTION(SUBSCRIBER_NAME,DATE_SUBSCRIBED,DATE_RETURNED,BOOK_ID)
values ('Mark',PARSEDATETIME('26-APR-2020','d-MMM-yyyy'),PARSEDATETIME('14-May-2020','d-MMM-yyyy'),'B4232');

insert into SUBSCRIPTION(SUBSCRIBER_NAME,DATE_SUBSCRIBED,DATE_RETURNED,BOOK_ID)
values ('Peter',PARSEDATETIME('22-JUN-2020','d-MMM-yyyy'),PARSEDATETIME('14-May-2020','d-MMM-yyyy'),'B1212');
